### PR TITLE
gubener: Enabled 2+5GHz Mesh networking

### PR DESCRIPTION
**Pull request by robertfoss**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
You want to mesh with the wifi of your core-router?

**Comment by robertfoss** [comment]
Yep! I only have this avm7530 device at my location at this moment. And some neighbors would like to run a ff-falter node until they get internet at home.

**Comment by PolynomialDivision** [comment]
lgtm

**Review by PolynomialDivision — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
Just to mention that, maybe it would also be possible to host multiple standlone wifi routers into one location by creating multiple "core routers", like you did. And multiple vlans with (but not required) the same vlan id. However, maybe @spolack sees "one location" as only having one core router. ;)

**Comment by PolynomialDivision** [comment]
Are you allowed to merge yourself?

**Comment by robertfoss** [comment]
No.

**Comment by robertfoss** [comment]
> Are you allowed to merge yourself?

No

**Comment by robertfoss** [comment]
> Just to mention that, maybe it would also be possible to host multiple standlone wifi routers into one location by creating multiple "core routers", like you did. And multiple vlans with (but not required) the same vlan id. However, maybe @spolack sees "one location" as only having one core router. ;)
> 
> Just some theoretical concept.
> 
> You could also directly place the routers into ansible and hope they will survive longer and maintain them here as separate locations. Not sure if you want that.

Just having one router is good for now. At least until I get proper near-field antennas.

**Pull request merged**
