### PR TITLE
wireless_profiles: OWE requires mandatory managment frame protection

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by Noki** [comment]
@PolynomialDivision https://github.com/freifunk-berlin/bbb-configs/pull/467 this disables the JSCPD linter, because we have duplication by design.

**Comment by pktpls** [comment]
I don't understand, I thought Transition Mode requires mandatory 80211w. OWE itself has been working fine from what I can tell

**Review by Noki — APPROVED** [review]
> I don't understand, I thought Transition Mode requires mandatory 80211w. OWE itself has been working fine from what I can tell

As far as I understand it, setting it to be optional `1` is/was the problem. Setting it to `2` is correct as it is mandatory. So this looks good to me.

**Comment by pktpls** [comment]
This doesn't fix Transition Mode (#426), I just tried 23.05-SNAPSHOT in Fritzbox 4040 and hit the same handshake bug: `received EAPOL-Key msg 4/4 in invalid state`.

The reason we switched 80211w from 2 to 1 in the past is that it can cause problems with 80211r roaming: https://github.com/openwrt/openwrt/issues/9181

Does this PR fix OWE for iOS? What does it fix? :-)

**Comment by pktpls** [comment]
Works fine without management frame protection :+1: see #426 our issue was some ipq40xx-specific thing which we can work around by using OpenSSL

**Pull request closed without merging**
