### PR TITLE
Add olsrd utils

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
This should after some days after all targets have those package available.

**Comment by spolack** [comment]
Please describe what is this for and how much it takes.

**Comment by PolynomialDivision** [comment]
It is a command line script that allows to easily debug olsr:
```
root@scharni-core:~# olsrd-neigh 
Local         Remote       vTime  LQ       NLQ      Cost     Host 
10.31.xxx.xxx 10.31.xxx.xxx 139972 1.000000 1.000000 1.000000 xxxx-core.olsr 
10.31.xxx.xxx 10.31.xx.xx 138429 1.000000 1.000000 1.000000 
```

**Comment by PolynomialDivision** [comment]
It should not take much space

**Pull request merged**
