### PR TITLE
Create LICENSE.md

### LINKED ISSUE #43: add a LICENSE file
Is the license of this project mentioned somewhere?

Anyway we should add a LICENSE file to the root of the repository.

### PR DESCRIPTION
**Pull request by Akira25**
Add a LICENSE for the ansible-repo. 

Fixes #43

### CODE REVIEW

**Review by pmelange — APPROVED** [review]
lgtm.  I would like @spolack , @PolynomialDivision or @freifunkoperator to merge this though

**Review by spolack — APPROVED** [review]
thank you for that contribution

**Comment by Akira25** [comment]
@spolack There are two approvals now. Could you please merge, or should I?

**Comment by spolack** [comment]
> @spolack There are two approvals now. Could you please merge, or should I?

I'd like to get an approval from @PolynomialDivision .

**Comment by PolynomialDivision** [comment]
ACK

**Pull request merged**
