### PR TITLE
uplink: add dnsqmasq to uplink gateways

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Dnsmasq is important to resolve olsr addresses. Add it to uplink gateways.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@pmelange that should fix everything

**Comment by pmelange** [comment]
I think that you should also have ```list notinterface {{ uplink['ifname'] }}``` in the ```config dnsmasq``` section.  This will prevent dnsmasq from being a DNS server on the public port.

**Comment by pmelange** [comment]
> I think that you should also have `list notinterface {{ uplink['ifname'] }}` in the `config dnsmasq` section. This will prevent dnsmasq from being a DNS server on the public port.

By the way, is ```uplink['ifname*]``` the device or the interface defined in /etc/config/network?  Because it needs to be the device which is listed in the dhcp config.

**Comment by pmelange** [comment]
for example, in l105-gw
```
config interface 'uplink'
        option ifname 'eth0'
        option proto 'static'
        option ipaddr '77.87.49.8/28'
        option gateway '77.87.49.1'
```

needs to be like this in the dhcp config
```
list notinterface 'eth0'
```

**Pull request merged**
